version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - angular
      - spring
  angular:
    image: ghcr.io/bbzblit/m322-frontend/m322-frontend:latest
    expose:
      - "80"
  spring:
    image: ghcr.io/bbzblit/m322-backend/m322-backend:latest
    expose:
      - "8080"
    environment:
      - MONGO_CONNECTION=mongodb://root:password@mongo:27017/admin
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password